export default {
  OPEN_NEW_MESSAGE: 'OPEN_NEW_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',
  CLEAR_ALL_MESSAGES: 'CLEAR_ALL_MESSAGES',
};
